### ISSUE TITLE
文件缺失寻求帮助

### ISSUE THREAD

**Issue by cherish-qinger** [YUEchn/front-end-code#1]
你好，我们查阅到您的ChinaVis2022很优秀，想借鉴部分可视化技术，请问一下您的[ChinaVis2022](https://github.com/YUEchn/ChinaVis2022)项目代码是完整的吗，复现过程中有出现文件缺失的情况，希望抽空回复一下，谢谢啦

**Comment by YUEchn** [comment]
已收到！
